version: "2.1"
services:
  flexget:
    image: cpoppema/docker-flexget
    container_name: flexget
    environment:
      - PGID=1000
      - PUID=1000
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission
      - TZ=Europe/London
      - FLEXGET_LOG_LEVEL=debug
    ports:
      - 5050:5050
    volumes:
      - ./services/flexget:/config
      - ./torrents:/downloads
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=flexger-user
      - PASS=flexger-password
    volumes:
      - ./services/transmission:/config
      - ./library:/downloads
      - ./torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./services/plex:/config
      - ./library:/tv
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped