schedules:
  - tasks: '*'
    interval:
      minutes: 1

web_server: yes
variables: secrets.yml

templates:
  tvshows:
    metainfo_series: yes
    notify:
      entries:
        message: |+
          *{{series_name}}*
          _{{series_season}} сезон {{series_episode}} серия_
          {{tvdb_ep_name}}
          [{{ tvdb_posters}}] {% if description is defined %}({{description}}){% endif %}
        via:
          - telegram:
              bot_token: '{? telegram.token ?}'
              parse_mode: markdown
              recipients:
                - username: '{? telegram.username ?}'
    set:
      path: '/downloads/{{series_name}}/Season {{series_season}}'
      content_filename: "{{ series_name }} - s{{ series_season|pad(2) }}e{{ series_episode|pad(2) }} - {{ tvdb_ep_name }}"
    thetvdb_lookup: yes
    transmission:
      host: '{? transmission.hostname ?}'
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
    regexp:
      reject_excluding:
        - 720p
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'

tasks:
  lostfilm:
    headers:
      cookie: '{? lostfilm.cookie ?}'
    lostfilm: yes
    template:
      - tvshows
    manipulate:
      - title:
          replace:
            regexp: '[^\x00-\x80]+'
            format: ''
    include: series-lostfilm.yml